# fly.toml app configuration file generated for transport-planner on 2023-11-20T03:23:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "transport-planner"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
